# this file is *not* meant to cover or endorse the use of travis, but rather to
# help confirm pull requests to this project.

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

# command to install dependencies
install:
  - pip install numpy
  - pip install matplotlib

# command to run tests
script:
  - pytest tests/test_simple.py

#notifications:
#  email: false
