# this file is *not* meant to cover or endorse the use of travis, 
# but rather to help confirm pull requests to this project.
# Specifying Python versions: https://docs.travis-ci.com/user/languages/python/

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build

# command to install dependencies
install:
  - pip install --upgrade setuptools
  - pip install numpy
  - pip install matplotlib

# command to run tests
script:
  - pytest tests/test_simple.py

#notifications:
#  email: false
